#! /bin/sh

echo $HOSTNAME | grep grendel32.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 4386 
else 
rsh grendel32.ece.ncsu.edu kill 4386 
 sleep 10 
rsh grendel32.ece.ncsu.edu kill -9 4386 
fi
