#! /bin/sh

echo $HOSTNAME | grep grendel31.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 7212 
else 
rsh grendel31.ece.ncsu.edu kill 7212 
 sleep 10 
rsh grendel31.ece.ncsu.edu kill -9 7212 
fi
