#! /bin/sh

echo $HOSTNAME | grep grendel27.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 4534 
else 
rsh grendel27.ece.ncsu.edu kill 4534 
 sleep 10 
rsh grendel27.ece.ncsu.edu kill -9 4534 
fi
