#! /bin/sh

echo $HOSTNAME | grep grendel27.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 11189 
else 
rsh grendel27.ece.ncsu.edu kill 11189 
 sleep 10 
rsh grendel27.ece.ncsu.edu kill -9 11189 
fi
