#! /bin/sh

echo $HOSTNAME | grep grendel25.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 19655 
else 
rsh grendel25.ece.ncsu.edu kill 19655 
 sleep 10 
rsh grendel25.ece.ncsu.edu kill -9 19655 
fi
