#! /bin/sh

echo $HOSTNAME | grep grendel32.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 5409 
else 
rsh grendel32.ece.ncsu.edu kill 5409 
 sleep 10 
rsh grendel32.ece.ncsu.edu kill -9 5409 
fi
