#! /bin/sh

echo $HOSTNAME | grep grendel25.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 18527 
else 
rsh grendel25.ece.ncsu.edu kill 18527 
 sleep 10 
rsh grendel25.ece.ncsu.edu kill -9 18527 
fi
