#! /bin/sh

echo $HOSTNAME | grep grendel27.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 14652 
else 
rsh grendel27.ece.ncsu.edu kill 14652 
 sleep 10 
rsh grendel27.ece.ncsu.edu kill -9 14652 
fi
