#! /bin/sh

echo $HOSTNAME | grep grendel31.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 20143 
else 
rsh grendel31.ece.ncsu.edu kill 20143 
 sleep 10 
rsh grendel31.ece.ncsu.edu kill -9 20143 
fi
