#!/bin/sh
total=0
pathsize=`/usr/bin/du -s --block-size=1 /afs/unity.ncsu.edu/users/z/zwmurray/ece546/proj_working/synopsys_custom/nor_5.icv.drc/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
group=0
group=`/usr/bin/du -s --block-size=1 /dev/shm/ICV_tmp_zwmurray_5843 | awk '{print $1}'`
echo $group > /dev/shm/ICV_tmp_zwmurray_5843/duse_group.tmp && \
mv /dev/shm/ICV_tmp_zwmurray_5843/duse_group.tmp /dev/shm/ICV_tmp_zwmurray_5843/duse_group
pathsize=`/usr/bin/du -s --block-size=1 /afs/unity.ncsu.edu/users/z/zwmurray/ece546/proj_working/synopsys_custom/nor_5.icv.drc/nor_5.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /afs/unity.ncsu.edu/users/z/zwmurray/ece546/proj_working/synopsys_custom/nor_5.icv.drc/run_details/duse_manager_res.tmp && \
mv /afs/unity.ncsu.edu/users/z/zwmurray/ece546/proj_working/synopsys_custom/nor_5.icv.drc/run_details/duse_manager_res.tmp /afs/unity.ncsu.edu/users/z/zwmurray/ece546/proj_working/synopsys_custom/nor_5.icv.drc/run_details/duse_manager_res
