#! /bin/sh

echo $HOSTNAME | grep grendel31.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 5843 
else 
rsh grendel31.ece.ncsu.edu kill 5843 
 sleep 10 
rsh grendel31.ece.ncsu.edu kill -9 5843 
fi
