#! /bin/sh

echo $HOSTNAME | grep grendel32.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 3151 
else 
rsh grendel32.ece.ncsu.edu kill 3151 
 sleep 10 
rsh grendel32.ece.ncsu.edu kill -9 3151 
fi
