#! /bin/sh

echo $HOSTNAME | grep grendel31.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 18688 
else 
rsh grendel31.ece.ncsu.edu kill 18688 
 sleep 10 
rsh grendel31.ece.ncsu.edu kill -9 18688 
fi
