#! /bin/sh

echo $HOSTNAME | grep grendel27.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 24492 
else 
rsh grendel27.ece.ncsu.edu kill 24492 
 sleep 10 
rsh grendel27.ece.ncsu.edu kill -9 24492 
fi
